export { default as facebook } from './facebook.png'
export { default as instagram } from './instagram.png'
export { default as tiktok } from './tik-tok.png'
export { default as github } from './github.png'
export { default as linkedin } from './linkedin.png'
export { default as twitter } from './twitter.png'
export { default as youtube } from './youtube.png'
export { default as userAvatar } from './user_avatar.png'
